# Generated by Django 5.2.1 on 2025-05-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
